version: '3.9'
services:

  # turtlebot3-ros:
  #   build: 
  #     context: ./
  #     target: turtlebot3-ros
  #   container_name: turtlebot3-ros
  #   environment:
  #     - "CSW_PYTHON=python3"
  #     - DISPLAY=${DISPLAY}
  #   volumes:
  #     - /tmp/.X11-unix:/tmp/.X11-unix
  #     - ./turtlebot3:/turtlebot3
  #   network_mode: "host"
  #   extra_hosts:
  #     - "optitrackPC:192.168.2.199"
  #   privileged: true
  #   devices:
  #     - '/dev:/dev'

  turtlebot3-ros2:
    build: 
      context: ./
      target: turtlebot3-ros2
    container_name: turtlebot3-ros2
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./turtlebot3:/turtlebot3
    network_mode: "host"
    extra_hosts:
      - "optitrackPC:192.168.2.199"
    privileged: true
    devices:
      - '/dev:/dev'
